server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
#         name: configClient
      server:
         git:
#           uri:  git@192.168.211.129:configCenter.git
           uri:  https://gitlab.com/Janloong-Doo/config-repo.git
           default-label: master
           username: xxx
           password: xxx
#           username: git
#           password: git
#           search-paths: config-repo
#           clone-on-start: true
#           native:
#             search-locations: E:\Projects\cloud\configCenter
#             default-label: asd
#
#  profiles:
#    active: dev

#actuator
#endpoints.mappings.sensitive=false  关闭单个的
#management.security.enabled=false  关闭所有鉴权

